In [3]:
from urllib.request import urlopen
from bs4 import BeautifulSoup as bs
import pandas as pd
import time
import sys

from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [4]:
def insert_row(df, my_row):
    """Insert a list in an existing DataFrame. The length of the list must be the same as the number of the columns in the DataFrame.
    -----------------
       Parameters
    -----------------
    df : the DataFrame in which we want to insert a new list as the last row of the DataFrame 
    my_row : the list we want to insert into the DataFrame
    
    -----------------
        Returns
    -----------------
    None
    """
    df.loc[len(df)] = my_row

In [5]:
# test getting data for page 4500
page_num = 4500
url = f"https://www.trustpilot.com/review/www.asurion.com?page={page_num}"
page = urlopen(url)
soup = bs(page, "html.parser")
evaluations = soup.findAll('div', attrs = {'class' : "styles_cardWrapper__LcCPA styles_show__HUXRb styles_reviewCard__9HxJJ"})

#print(evaluations)
df_evals = pd.DataFrame(columns = ['titre','nom','stars','localisation','nb_reviews','date_review','date_experience','comment'])
for e in evaluations:
        titre_ = e.find('h2', {'class': 'typography_heading-s__f7029 typography_appearance-default__AAY17'})
        titre = titre_.text if titre_ is not None else ''
        
        nom_ = e.find('span', {'class': 'typography_heading-xxs__QKBS8 typography_appearance-default__AAY17'})
        nom = nom_.text if nom_ is not None else ''
        
        stars_ = e.find('img')['alt']
        stars = stars_ if stars_ is not None else ''
        
        localisation_ = e.find('div', {'class': 'typography_body-m__xgxZ_ typography_appearance-subtle__8_H2l styles_detailsIcon__Fo_ua'}).find('span')
        localisation = localisation_.text if localisation_ is not None else ''
        
        nb_reviews_ = e.find('span', {'class': 'typography_body-m__xgxZ_ typography_appearance-subtle__8_H2l'})
        nb_reviews = nb_reviews_.text if nb_reviews_ is not None else ''
        
        date_review_ = e.find('time')['datetime']
        date_review = date_review_ if date_review_ is not None else ''
        
        date_experience_ = e.find('p',{'class':'typography_body-m__xgxZ_ typography_appearance-default__AAY17'})
        date_experience = date_experience_.text if date_experience_ is not None else ''
        
        comment_ = e.find('p', {'class': 'typography_body-l__KUYFJ typography_appearance-default__AAY17 typography_color-black__5LYEn'})
        comment = comment_.text if comment_ is not None else ''
        
        insert_row(df_evals, [titre,nom,stars,localisation,nb_reviews,date_review,date_experience,comment])
        
df_evals.head()

,titre,nom,stars,localisation,nb_reviews,date_review,date_experience,comment
0,Tiddy,Rarar R,Rated 5 out of 5 stars,US,1 review,2017-01-08T05:10:16.000Z,"Date of experience: January 08, 2017","It was amazing, thanks!!!"
1,Love Asurion,KENNETHHAMMETT H,Rated 5 out of 5 stars,US,1 review,2017-01-08T05:00:45.000Z,"Date of experience: January 08, 2017",Great service
2,Courteous and patient!,TONYA H,Rated 5 out of 5 stars,US,2 reviews,2017-01-08T04:58:05.000Z,"Date of experience: January 08, 2017","Very thorough, explaining each step, making su..."
3,Promises kept!,CHESTER E,Rated 5 out of 5 stars,US,1 review,2017-01-08T03:24:50.000Z,"Date of experience: January 08, 2017",The customer service rep was so patient and he...
4,new phone,MICHAEL H,Rated 5 out of 5 stars,US,1 review,2017-01-08T02:51:32.000Z,"Date of experience: January 08, 2017",Easy to get new phone